server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certificat.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tweetx.info

logging:
  level:
    root: warn

vaadin:
  launch-browser: true
  allowed-packages: 
    - com.vaadin
    - org.vaadin
    - com
  productionMode: @vaadin.production.mode@
  frontend:
    hotdeploy: @vaadin.frontend.hotdeploy@
