spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: info

vaadin:
  productionMode: false
  frontend:
    hotdeploy: true
  launch-browser: true
  allowed-packages:
    - com.vaadin
    - org.vaadin
    - com
