server:
  port: 8081

logging:
  level:
    root: warn

vaadin:
  launch-browser: true
  allowed-packages: 
    - com.vaadin
    - org.vaadin
    - com
  productionMode: @vaadin.production.mode@
  frontend:
    hotdeploy: @vaadin.frontend.hotdeploy@
