name: Build and Deploy JAR

# Trigger the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set KEY_STORE_PASSWORD environment variable
      run: echo "KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}" >> $GITHUB_ENV

    - name: Set up SSH key
      run: |
        echo "${{ secrets.REMOTE_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key

    - name: Stop the antix-app service
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} "sudo systemctl stop antix-app.service"
    
    - name: Remove existing files in /opt/tweetx
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} "sudo rm -rf /opt/tweetx/*"

    - name: Deploy JAR to remote server
      run: |
        scp -i ssh_key -o StrictHostKeyChecking=no ./target/antix-2025.jar root@${{ secrets.REMOTE_HOST }}:/opt/tweetx/

    - name: Verify JAR on remote server
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} "ls -lh /opt/tweetx/antix-2025.jar"
    
    - name: Start the antix-app service
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} "sudo systemctl start antix-app.service"

